[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32@~6.7.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
board_build.variants_dir = variants
board_build.variant = m5stack_cores3
platform_packages =
  platformio/framework-arduinoespressif32@~3.20016.0
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  m5stack/M5Unified@^0.1.15

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<*> -<main.cpp> -<SettingsStore.cpp> -<SdBackup.cpp> -<Transport.cpp>
